services:
  # GUI Service
  gui:
    build: ./gui
    ports:
      - 5001:5000

  # Auth Service
  auth:
    build: ./services/auth
    ports:
      - 5002:5000
    depends_on:
      - auth_persistence
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DATABASE_HOST=auth_persistence

  auth_persistence:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - auth_persistence-data:/var/lib/postgresql/data
      - ./services/auth/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Events Service
  events:
    build: ./services/events
    ports:
      - 5003:5000
    depends_on:
      - events_persistence
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DATABASE_HOST=events_persistence

  events_persistence:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - events_persistence-data:/var/lib/postgresql/data
      - ./services/events/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Invitations Service
  invitations:
    build: ./services/invitations
    ports:
      - 5004:5000
    depends_on:
      - invitations_persistence
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DATABASE_HOST=invitations_persistence

  invitations_persistence:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - invitations_persistence-data:/var/lib/postgresql/data
      - ./services/invitations/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  calendars:
    build: ./services/calendars
    ports:
      - 5005:5000
    depends_on:
      - calendars_persistence
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DATABASE_HOST=calendars_persistence

  calendars_persistence:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - calendars_persistence-data:/var/lib/postgresql/data
      - ./services/calendars/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  auth_persistence-data:
  events_persistence-data:
  invitations_persistence-data:
  calendars_persistence-data:
