version: "3.9"
services:
  # GUI Service
  gui:
    build: ./gui
    ports:
      - 5001:5000

  # Users Service
  users:
    build: ./services/users
    ports:
      - 5002:5000
    depends_on:
      - users_persistence
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DATABASE_HOST=users_persistence

  users_persistence:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - users_persistence-data:/var/lib/postgresql/data
      - ./services/users/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  users_persistence-data:
